# Generated by Django 2.1 on 2019-09-18 14:24

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, verbose_name='名称')),
                ('domain', models.CharField(max_length=128, null=True, verbose_name='通用名称')),
                ('orther_domain', models.TextField(blank=True, max_length=4096, null=True, verbose_name='备用名称')),
                ('organization_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Organization Name')),
                ('serial_number', models.CharField(blank=True, max_length=64, null=True, verbose_name='Serial number')),
                ('issued_by', models.CharField(blank=True, max_length=64, null=True, verbose_name='Issued By')),
                ('cert_type', models.CharField(blank=True, max_length=4, null=True, verbose_name='证书类型')),
                ('method', models.BooleanField(choices=[(0, '域名'), (1, '证书')], default=0, verbose_name='Cert Detection Approach')),
                ('domain_url', models.CharField(blank=True, max_length=128, null=True, verbose_name='域名')),
                ('crt_file', models.TextField(blank=True, null=True, verbose_name='Crt File')),
                ('key_file', models.TextField(blank=True, null=True, verbose_name='Key File')),
                ('notbefore', models.CharField(blank=True, max_length=24, null=True, verbose_name='Not Before')),
                ('notafter', models.CharField(blank=True, max_length=24, null=True, verbose_name='Not After')),
                ('remain_days', models.IntegerField(blank=True, null=True, verbose_name='Remaining Days')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date created')),
                ('comment', models.TextField(blank=True, max_length=128, null=True, verbose_name='Comment')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Contact')),
            ],
            options={
                'db_table': 'certs',
            },
        ),
    ]
